services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8153:80"
      - "8443:443"
    volumes:
      - ./frontend/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs/fullchain.pem:/etc/ssl/certs/fullchain.pem:ro
      - ./certs/privkey.pem:/etc/ssl/private/privkey.pem:ro
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    expose:
      - "8080"
    depends_on:
      - db
    restart: unless-stopped
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "8432:5432"

volumes:
  pgdata:
